nerves-project/nerves_runtime

- lib/nerves_runtime/shell/evaluator.ex
- lib/nerves_runtime/shell/server.ex
Before:
sh[1]>
After:
/home/fhunleth/nerves/nerves_runtime[1]>
> Print out working directory in shell prompt

- Makefile
Even though nerves_runtime won't run on Macs for real, there's still
quite a bit that you can do (make run "mix docs" and "mix compile"), so 
don't error out.
> Update Makefile to allow builds on OSX

- Makefile
Make prints the comment about running suid'ing the port binary when
crosscompiling even though it doesn't do it. Since calling setuid
executables can be legitimately concerning, refactor the code so that
it's more obvious that this isn't happening.
> Remove the suid print when crosscompiling

- README.md
> Replace `bootloader` docs with `shoehorn` docs.

- .formatter.exs
- mix.exs
- src/erlcmd.c
- src/erlcmd.h
- src/uevent.c
This doesn't actually run the formatter. It's just the updates to make `mix format` work out of the box. 
The C format updates look decent to me. There were quite a few places where spacing was unaligned, but that was it.
Everyone ok with this?
> Enable "mix format" for C and Elixir

- lib/nerves_runtime.ex
- lib/nerves_runtime/application.ex
- lib/nerves_runtime/device.ex
- lib/nerves_runtime/helpers.ex
- lib/nerves_runtime/init.ex
- lib/nerves_runtime/kernel.ex
- lib/nerves_runtime/kernel/uevent.ex
- lib/nerves_runtime/kv.ex
- mix.exs
- test/init_test.exs
- test/kv_test.exs
- test/log_tailer_test.exs
We might as well get it over with before someone else submits the PR for us.
> Run `mix format`

- CHANGELOG.md
- README.md
- mix.exs
- mix.lock
This collects a few minor changes and bumps the release so that a few commits can be more widely used.
> v0.6.1 release

- lib/nerves_runtime.ex
If `:logger` isn't running, then the reboot, shutdown, halt commands
fail. This tries to salvage things by always calling `:init.stop`.
> Try to call :init.stop on shutdown

- CHANGELOG.md
- lib/nerves_runtime.ex
- lib/nerves_runtime/device.ex
- lib/nerves_runtime/helpers.ex
- lib/nerves_runtime/init.ex
- lib/nerves_runtime/kernel.ex
- lib/nerves_runtime/kernel/uevent.ex
- lib/nerves_runtime/kv.ex
- lib/nerves_runtime/kv/mock.ex
- lib/nerves_runtime/kv/uboot_env.ex
- lib/nerves_runtime/log/kmsg_tailer.ex
- lib/nerves_runtime/log/parser.ex
- lib/nerves_runtime/log/syslog_tailer.ex
- lib/nerves_runtime/output_logger.ex
- lib/nerves_runtime/uboot_env.ex
- lib/nerves_runtime/uboot_env/config.ex
- lib/nerves_runtime/uboot_env/tools.ex
- src/uevent.c
This PR comes after #88 and #89. It makes a pass over the specs and docs. 
Unfortunately, more work is still needed, but I timed out for today and this should be an improvement over the existing docs.
> Specs and docs

- lib/nerves_runtime/log/parser.ex
This change is mostly a matter of preference to use pattern matching
rather than regular expression matches. It seems like it ought to be faster, but
devices probably don't generate enough log messages to see a difference.
> Refactor syslog parser to use pattern matching

- lib/nerves_runtime/init.ex
> Fix docs describing partition initialization

- lib/nerves_runtime/init.ex
- lib/nerves_runtime/kernel/uevent.ex
- lib/nerves_runtime/kv.ex
- lib/nerves_runtime/log/kmsg_tailer.ex
- lib/nerves_runtime/log/syslog_tailer.ex
While there weren't any compiler issues that @impl catches since this
code isn't new, it does improve the generated docs. The init docs no
longer show the verbose GenServer.init text.
> Add @impl to GenServer callbacks

- lib/nerves_runtime/device.ex
This changes the uevent discovery process to find all of the uevent
files and then to write "add" to them. Previously, "add" was written to
them while finding them.
The reason that this is ok is because when the discovery process is
started, the uevent port has been started. Therefore, if a device were
to get added during the file discovery process, it would already have
sent a uevent that the uevent port would have seen.
This change appears to noticeably speed up discovery time when combined
with #107 on the Raspberry Pi Zero.
> Find the uevent files and then add

- lib/nerves_runtime/kernel/uevent.ex
Previously the discovery was being done synchronously in the UEvent
GenServer. This would cause uevents messages from the port process to
queue up in the mailbox. The once discovery was done, they'd be
processed in a burst. With this change, the discovery happens in another
process. UEvents get processed as they come in. This opens up some
parallelism. The most obvious difference is that kernel modules get
loaded more quickly.
> Run uevent discovery asynchronously

- lib/nerves_runtime/kernel/uevent.ex
- src/uevent.c
This avoids a String.split which cuts the number of reductions by about
a third in Nerves.Runtime.Kernel.Uevent (~18M to 13M for a BBB-based
board)
> Convert devpath to scope in C

- .circleci/config.yml
* Bump Elixir and Erlang versions
* Run Dialyzer
* Run hex.build
> CI script updates

- Makefile
- lib/nerves_runtime/kernel/uevent.ex
- lib/nerves_runtime/log/kmsg_tailer.ex
- src/kmsg_tailer.c
- src/nerves_runtime.c
- src/uevent.c
This PR is in prep for a PR that adds one more port executable.
> Switch to use multi-call port executable

- CHANGELOG.md
- mix.exs
I applied the comments from https://github.com/nerves-project/nerves_runtime/pull/132
> v0.9.4 release

- .circleci/config.yml
- .circleci/md-style.rb
- .dialyzer_ignore.exs
- .formatter.exs
- CHANGELOG.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- lib/nerves_runtime/application.ex
- lib/nerves_runtime/init.ex
- lib/nerves_runtime/kernel/uevent.ex
- lib/nerves_runtime/log/kmsg_tailer.ex
- lib/nerves_runtime/log/syslog_tailer.ex
- mix.exs
- mix.lock
I'm on a bus, so none of this is tested. 
Followup PRs will include doc and spec updates
> Update CI, fix Markdown and Dialyzer

- README.md
> Added uevent/udev documentation

- lib/nerves_runtime/application.ex
Fixes #166 
I am considering moving the comment about rngd and haveged into the README and adding a note about which Buildroot packages provide them. Would this be OK?
> Add haveged as fallback if starting rngd fails

- .dialyzer_ignore.exs
- lib/nerves_runtime.ex
Based on discussions from #184 & #180
> Add Nerves.Runtime.validate_firmware/0

- CHANGELOG.md
- mix.exs
- mix.lock
- Bump earmark_parser
- Fix undefined reference warnings on the changelog
- v0.11.4 release
> v0.11.4 release

- lib/nerves_runtime/output_logger.ex
- test/nerves_runtime/output_logger_test.exs
This also adds specs and makes minor adjustments to the code for
consistency.
> Fix string trimming and add test to OutputLogger

- lib/nerves_runtime/init.ex
~~If we formatted and it successfully mounted, we need to restart before using the partition to prevent errors. This typically only occurs on first boot~~
Edit (after much discussion below):
After a fresh SD card burn, the application partition may not be
formatted which means the shell history will fail to start preventing
history being saved until a reboot.
This change detects if the application partition needed to be formatted
and resets the shell history env var to enable history again once
the disk was successfully formatted and mounted. This will allow
history to be saved even on first boot.
> Set `:shell_history` after formatting application partition on first boot

- lib/nerves_runtime/kernel/uevent.ex
- src/uevent.c
This saves a trip from C -> Elixir and back to run modprobe for
dynamically loading kernel modules. Since it's unknown whether modprobe
should be called for any new device, it always has to be called. This
ends up being 50-100 invocations or more depending on the device.
GRiSP 2 has a relatively small number of devices (~50), but moving this
to C results in about 1 second reduction of boot time. Boot time here is
for when the critical applications are all started (Nerves.Runtime,
VintageNet, etc.)
Calling in C has a number of advantages as well. First of all, stdio can
be redirected to `/dev/null` since we know that we're going to throw
away any output anyway. Elixir must capture this output and then toss
it. Secondly, starting processes is cheaper in C anyway, since Erlang
has to do some …
> Move modprobe invocation to C

- src/uevent.c
This is mostly a cleanup of the ordering of events in the system, but it
might fix a subtle issue.
The general idea behind this code is to trigger uevent reports to be
sent over netlink. We may have started listening for reports after
events were sent, so to be safe, everything needs to be told to send an
event again. The way this is done is to scan `/sys/devices` and write
`add` to every `uevent` file.
The original file processing order matched whatever was on the
filesystem. This does not look deterministic (and that makes sense that
it wouldn't since that's extra work). Files were also processed in post
order, so USB devices would get their `add`'s written to them before the
USB bus devices that they're on, etc.
This commit changes the logic in two ways:
1. Parent `uevent` files are …
> Update device scan for determinism and container first

- src/uevent.c
Each call to modprobe is a fork and exec. Then after that, modprobe
needs to read the modalias database. This change batches up calls to
modprobe so that they can be done in one go.
Here are some test runs:
BBB clone 1 -> 78 modprobes became 9
BBB clone 2 -> 83 modprobes became 11
GRiSP2      -> 73 modprobes became 8
RPi0        -> 51 modprobes became 5
This has a small effect on reducing boot time. Rough timing seemed to
make it less than a second.
Why is modprobe called so much? It's because there's no wait to know
whether a kernel module should be loaded when a device gets reported.
The only way to tell is to check the modalias against the kernel module
database.
> Batch up modprobe invocations

- lib/nerves_runtime/heart.ex
- test/nerves_runtime/heart_test.exs
This makes it easier to get information from Nerves Heart.
> Add Nerves Heart utility functions

- lib/nerves_runtime/heart.ex
The `snooze/0` function tells Nerves heart to ignore missing pings from
the Erlang VM and to pet the hardware watchdog for the next 15 minutes.
This is useful for debugging partial hang-type issues don't prevent
debug, but do cause Heart health callbacks to take a long time.
> Add support for snoozing Nerves heart

- .circleci/config.yml
- lib/nerves_runtime/heart.ex
- lib/nerves_runtime/init.ex
- test/nerves_runtime/heart_test.exs
Re: https://github.com/nerves-project/nerves/issues/873
> Support Elixir 1.15 / OTP 26.0

- .circleci/config.yml
Bring the CI tested Elixir/OTP versions to the latest
> Update CI Versions

- lib/nerves_runtime/kv.ex
This allows for more accurate running firmware slot detection. Since
it's possible for Nerves systems to not have an ops.fw, it falls back to
the previous way.
> Use ops.fw to determine the active firmware slot
