lib/nerves_runtime/device/adapter/connection.ex, lib/nerves_runtime/device/handler.ex
I just noticed that this callback was missing from the device handler behaviour.
=> Add missing device argument to handle_data_in callback in connection behaviour

lib/nerves_runtime/shell.ex, lib/nerves_runtime/shell/evaluator.ex, lib/nerves_runtime/shell/server.ex
This started as a collection of minor updates to the docs and then I renamed the shell prompt. As I think that you're aware, I have a personal bias against the word "host" so I attempted to find another word for the shell prompt. E.g., "sh", since the shell is hardcoded to "sh". In the future if the shell becomes configurable, naming the prompt after the program being run seemed reasonable. If this is controversial, I'll break this PR in two since the doc updates would be nice to have since I couldn't find info on starting the shell anywhere else.
=> Shell documentation and naming updates

lib/nerves_runtime/shell.ex, lib/nerves_runtime/shell/server.ex
This addresses issue #5. With this change, all that you need to type is `s sh` to get to the command shell.
=> Add shortcut for starting sh shell and reminder

.iex.exs, CHANGELOG.md, README.md, lib/nerves_runtime/application.ex, lib/nerves_runtime/device.ex, lib/nerves_runtime/init.ex, lib/nerves_runtime/kernel/uevent.ex, lib/nerves_runtime/kv.ex, mix.exs, test/init_test.exs, test/kv_test.exs
Adds Init and KV workers. Supports formatting application data partitions by reading from the uboot env block provided fwd from the fwup.conf
=> Init and KV Workers

README.md, lib/nerves_runtime/kernel.ex, lib/nerves_runtime/kernel/uevent.ex, mix.exs, mix.lock
system_registry 0.3.0 adds update_in/3 which lets us reasonably maintain lists as values. This means that we can logically represent the devices in the systems as both 
` [:state, "devices", "platform", "i8042", "serio0", "input", "input1", "input1::capslock"]`
and aliased in its subsystem
```
[:state, "subsystems", "leds"] -> [[:state, "devices", "platform", "i8042", "serio0", "input", "input1", "input1::capslock"]]
```
`modprobe` will be called on the uevent `modalias` if it exists by default. Added functionality to disable autoload through the application configuration.
```elixir
config :nerves_runtime, :kernel,
autoload_modules: false
```
=> Subsystems and modalias

lib/nerves_runtime/init.ex
It was already added to the opts map, so adding it again just messed it
up. This fixes a failed mount that luckily would get ignored at
initialization except for a print message.
=> Fix mounted_state initialization

README.md
These fields are used by code, usually in nerves_runtime, so it's nice to document them up front.
=> Document firmware official metadata fields

src/erlcmd.h
Work around message size segfaults for when receiving uevent messages with many attributes / long modalias names
=> increase message size to 2048

README.md, lib/nerves_runtime/helpers.ex
These are some utilities that I like to use at IEx prompt when running Nerves. There's certainly more that can be added, but I wanted to get started with some simple ones to get a feel for what people thought.
Here's some of the logic:
1. How many times have you typed `:os.cmd('dmesg')` only to forget to `|> IO.puts` so that the output is readable? `cmd/1` fixes that. It also fixes an issue that happens to me every time switch back and forth to Erlang which is that my fingers type double quotes instead of single quotes.
2. Lots of numbers and binaries I work with are more easily read in hex. See the `hex/1` utility.
3. Graceful reboot is cool, but sometimes I don't want to wait. Therefore, `reboot!/0`.
Also, @mobileoverlord tells me that he's working on a fix to IEx so that `h cmd` works. …
=> Add IEx helpers

lib/nerves_runtime/helpers.ex
Running File.write!/2 seemed easy enough until the first typo. Adding an
install helper fixes this problem.
=> Add install helper to avoid typos

lib/nerves_runtime/init.ex
This works around an issue with newer versions of util-linux that now
call the blocking getrandom(). This can hold up formatting of the
application partition indefinitely, which then holds up network
initialization. All of this for UUID generation (and a hash table seed).
=> Force UUID on application partition

README.md
It looks like `earmark` is barfing on the table formatting in the readme when generating the docs for hex. 
per https://github.com/pragdave/earmark/blob/master/README.md#tables
>Currently we assume there are always spaces around interior vertical bars. It isn't clear what the expectation is.
https://hexdocs.pm/nerves_runtime/readme.html#nerves-system-and-firmware-metadata
Screenshot from hex docs:
=> fix table formatting in readme

CHANGELOG.md, Makefile, README.md, config/config.exs, lib/nerves_runtime/application.ex, lib/nerves_runtime/log_tailer.ex, src/log_tailer.c, test/log_tailer_test.exs
I'm interested in feedback from others on this, in particular whether you think it should do less or do the same thing in a different way. For example, I thought it would be useful to parse out the syslog priority so we can pass it to Logger as metadata, which would be useful for filtering.
If you turn on `:all` metadata in `Logger`, it generates kernel messages like this:
```elixir
00:00:09.953 pid=<0.118.0> application=nerves_runtime module=Nerves.Runtime.LogTailer function=handle_message/2 file=/Users/greg/projects/nerves/nerves_runtime/lib/nerves_runtime/log_tailer.ex line=68 type=kmsg facility=kernel severity=Informational timestamp=1970-01-01T00:00:09.834640Z [info]  [    0.000000] Booting Linux on physical CPU 0x0
```
And if you do something like:
```elixir
:os.cmd('echo "test" | …
```
=> Add a basic syslog and kmsg tailer

lib/nerves_runtime/application.ex, lib/nerves_runtime/log_tailer.ex, mix.lock, src/erlcmd.c, src/erlcmd.h, src/log_tailer.c, src/uevent.c
Various small updates to the logger. It's easiest to look at the individual commits. I think that everything is very minor and uncontroversial with the possible exception of the first commit. The first commit removes the LogTailer.Kmsg and LogTailer.Syslog methods. This was instigated by an Elixir 1.6 warning about the missing init method.
=> Logger updates

lib/nerves_runtime/helpers.ex
This fixes the cmd helper so that it doesn't wait until the program it
calls is done before printing the output. This makes it possible to run
slow programs and not think that the system is hanging. As a bonus, the
exit code is returned now.
=> Improve cmd helper to be interactive

README.md, lib/nerves_runtime/helpers.ex
Even though the kernel messages are logged, I so often run "dmesg" that
it seemed like a good command to add as a helper.
=> Add dmesg to the helpers; update install message

lib/nerves_runtime.ex, lib/nerves_runtime/init.ex, lib/nerves_runtime/output_logger.ex
I figured out that some of the commands invoked logs its output directly into linux console.  In the future, I want to have some kind of splash screen, so I will not able to see what was logged there. 
This PR address this issue. Will redirect all commands invoked by `nerves_runtime` output into logger with `:info` level.
=> Log commands output into logger

lib/nerves_runtime/kv.ex
It is impossible to parse multi line values from the uboot env dump of `fw_printenv`. If running on OTP 21, we can read the UBoot env blocks directly and parse them on the null byte.
=> Read the uboot env directly if running OTP 21

mix.exs
runtime_false does not propigate through hex. All hex packages are built using the production environment, therefore, changing the level of dependency to only dev will remove them from the application spec.
=> Set dialyxir and elixir_make to only: :dev

config/config.exs, lib/nerves_runtime.ex, lib/nerves_runtime/application.ex, lib/nerves_runtime/kv.ex, lib/nerves_runtime/kv/mock.ex, lib/nerves_runtime/kv/uboot_env.ex, test/kv/uboot_env_test.exs, test/kv_test.exs, test/test_helper.exs
This PR disables most of the main supervisor children in `Nerves.Runtime` and allows the `Nerves.Runtime.KV` to be mocked with data by providing an application config.
```
config :nerves_runtime, :modules, [
{Nerves.Runtime.KV.Mock, %{"key" => "value"}}
]
```
=> Mock modules when MIX_TARGET = host

lib/nerves_runtime/kernel/uevent.ex
This PR removes modifying the device tree representation in system_registry on uevent change actions. The change action represents when a devpath's properties change and we are only interested in when the devpath itself changes which is already handled by the uevent move action.
=> Remove uevent change action and silence logger on unmatched uevents

lib/nerves_runtime/kv.ex, lib/nerves_runtime/kv/uboot_env.ex, lib/nerves_runtime/uboot_env.ex, lib/nerves_runtime/uboot_env/config.ex, lib/nerves_runtime/uboot_env/tools.ex, test/kv/uboot_env_test.exs, test/uboot_env_test.exs
This adds the ability to write to the uboot env from elixir. If you are on OTP 21, it will write directly to the uboot env or fall back to calling `fw_setenv` on the command line.
=> Add put/2 for writing to uboot-env and refactor

mix.exs
I got an unexpected error when running `mix test` that was due to `dialyxir`. I didn't track it down and it's not happening now. I didn't think that `dialyxir` was needed for test, though, so this removes it.
=> Remove dialyxir from test deps

lib/nerves_runtime/device.ex, lib/nerves_runtime/kernel/uevent.ex
This removes a decent amount of data structure operations and triggers
uevents as the files are found. This causes the add notifications to
occur sooner and this has the side-effect of bringing up networking more
quickly on boot.
=> Send uevents on directory traversal

lib/nerves_runtime/helpers.ex
Since `nerves_runtime` is a required dependency for all Nerves projects,
we had to be careful what was included in it. This made it difficult to
add more helpers since the bar was so high. Another desired feature was
to be able to compile out the helpers for prod builds. This isn't
possible if the helpers are in `nerves_runtime`. This change removes the
helpers and leaves a note for anyone who has the helpers automatically
being included in an `iex.exs` file so that updating `nerves_runtime`
doesn't accidentally break their build.
Fixes #32.
=> Move Nerves.Runtime.Helpers to toolshed project

lib/nerves_runtime/application.ex, lib/nerves_runtime/kernel/uevent.ex
I got tricked by the `start_link` call thinking that UEvent always got a list. It was being sent a nil. This change changes where the nil was coming from and tightens the spec to make things more clear.
=> Always use a keyword list for Uevent options

src/uevent.c
SYNTH_UUID is a relatively new addition to the uevent reports that lets
applications distinguish between real events and those events that were
generated by writing the uevent file. The distiction between synthetic
and real events isn't used and this information isn't useful in
SystemRegistry, so strip it off. This seems to reduce SystemRegistry
reductions by 10%.
=> Ignore SYNTH_UUID in uevent reports

README.md, lib/nerves_runtime/kernel/uevent.ex
It's now possible to have `uevents` enabled so that kernel modules can
be auto-loaded without system_registry integration. Add the following
to your configuration to do this:
```elixir
config :nerves_runtime, :kernel,
use_system_registry: false
```
=> Add option to disable system_registry integration

lib/nerves_runtime/log/parser.ex
This fixes a warning when generating the docs.
=> Fence off text that looks like HTML

src/kmsg_tailer.c
Use sendfile(2) to avoid copying kernel log messages through the
kmsg_tailer userland application and avoid the need for the temporary
buffer.
=> Avoid copy through userland

Makefile, lib/nerves_runtime/device.ex, lib/nerves_runtime/kernel/uevent.ex, lib/nerves_runtime/log/kmsg_tailer.ex, src/kmsg_tailer.c, src/nerves_runtime.c, src/uevent.c, src/uevent_discover.c
This change greatly reduces syscalls for the initial device discovery
and discovery completes 10 seconds earlier on a simple Raspberry Pi
Zero build. This change does not appear to affect how early a user can
log into Elixir CLI, though.
=> Move the initial uevent discovery trigger to C

lib/nerves_runtime/kernel/uevent.ex
This removes the path lookup for modprobe and prevents someone from
putting an alternative modprobe earlier in the path lookup.
=> Use absolute path to modprobe

src/uevent.c, src/utils.h
I can only reproduce an overload on a 32-core x86_64 machine. What
happens is that libmnl returns an error from the recv call that
indicates that the kernel internally has dropped a notification. The
overload is triggered in the initial scan of hardware. It seems like it
should be impossible to trigger in any other real hardware insertion and
removal scenario.
Before this fix, the behavior was to exit the port process. This would
cause it to be re-started due to supervision. Since the hardware scan
must happen again since devices could have been inserted between the
crash and the restart, the scan is kicked off and the port process exits
again. Restart intensity is reached and total failure. Losing one or two
notifications bothers me greatly, but it seems like a far better
solution than …
=> Handle uevent overload more gracefully

src/uevent.c
This seems to only affect the x86_64 system. The error is:
```
src/uevent.c: In function 'uevent_discover':
src/uevent.c:276:19: error: 'PATH_MAX' undeclared (first use in this function); did you mean 'AF_MAX'?
char path[PATH_MAX] = "/sys/devices";
^~~~~~~~
AF_MAX
```
=> Fix compiler error from PATH_MAX

README.md
* Changes `nerves_validated` to `nerves_fw_validated` in doc
* Changes `nerves_autovalidate` to `nerves_fw_autovalidate` in doc
=> Fix some incorrect variables in doc

lib/nerves_runtime/kv.ex, lib/nerves_runtime/kv/mock.ex, lib/nerves_runtime/kv/uboot_env.ex
This PR closes #136 by adding a public API to the KV module for updating the firmware metadata.
The PR is not quite done (the doctests are broken and I haven't added new tests), but  I'd like to hear if I am taking this in the right direction.
Specifically, the API here does not support putting a key to the active partition by automatically adding the slot prefix. Should this be added to mirror `get_active/1`?
=> Add API to KV for writing to the firmware metadata

README.md, lib/nerves_runtime/kv.ex, lib/nerves_runtime/kv/mock.ex
I noticed that the old way of setting mock data is not longer supported. So this changes the docs with the correct way of specifying KV.Mock data.
Also adds `@callback put(state)` module attribute in `Nerves.Runtime.KV` since that is now a function which will be called on the dynamically defined module and should be expected in the contract.
=> Clarify docs for using Nerves.Runtime.KV.Mock

lib/nerves_runtime/init.ex
This also fixes the pattern mismatch for the return status code.
This addresses an issue where :nerves_runtime would exit due to an unmatched call to System.cmd/3.
Initially reported: https://elixirforum.com/t/missing-essential-processes-in-nerves-system/22945
=> Fix exception on init when mounting the application data partition

.dialyzer_ignore.exs, lib/nerves_runtime.ex
Previously this would raise and eventually cause `nerves_runtime` to be
stopped. This would stop RingLogger which would make seeing the error
message really hard. Errors are still returned and log messages written
so it should be easier to spot missing commands in Nerves systems in the
future.
=> Log and return an error if a command isn't found

Makefile, src/uevent.c
This PR increases the number of uevent path segments from 16 to 32 and fixes an error where the uevent port could construct a malformed term and cause the uevent port process to exit with an Argument error when trying to decode the binary to terms.
=> Increase uevent path segments

src/kmsg_tailer.c
This fixes nerves_runtime restarts generating kmsg_tailer zombie apps by
exiting if anything happens to stdin.
Fixes #152.
=> kmsg_tailer: exit on stdin errors

Makefile, mix.exs
Using MIX_APP_PATH cleans up the paths that get printed when building.
This also removes the check for whether `make` is being called directly,
since the Makefile is smart enough to detect this and call `mix`
automatically if this happens.
=> Switch to MIX_APP_PATH; remove unneeded check

.circleci/config.yml
CI is failing due to a Ruby version mismatch.
=> Remove Markdown lint for now

src/kmsg_tailer.c, src/uevent.c
Just in case there's ever a fork/exec added in the future, O_CLOEXEC
will already be around to close open file handles.
=> Add O_CLOEXEC proactively

mix.exs, mix.lock
uboot_env 0.2.0 contains a breaking change from 0.1.1, but the breaking
change does not affect nerves_runtime. This commit makes it possible to
use either version.
The main reason to update to 0.2.0 is that it significantly reduces the
amount of memory garbage that gets generated when parsing and writing
environment blocks. On one production system the garbage created was in
the low megabytes which one easily bump any process that called
uboot_env to the top of the list.
=> Support uboot_env 0.2.0

README.md, lib/nerves_runtime/init.ex
Currently only a few systems used `nerves_fw_validated` and its  a manual process in `fwup.conf` to setup and check in the context of autoreverts. Then that variable gets checked on next boot to determine if a revert should happen.
However, I think this is a little too early in the startup (i.e. we immediately set this variable, but something later in the startup but before runtime fails).
So this sets it during initialization of `Nerves.Runtime` to help catch that zone of errors that might otherwise be missed. If we're to this initialization, we're pretty confident the fw is good.
It also allows disabling autovalidation in the config so that the application can handle the logic check even later.
Also, I didn't change any documentation because it needs a pretty big overhaul. I have a …
=> Autovalidate fw on startup

.dialyzer_ignore.exs, lib/nerves_runtime.ex, lib/nerves_runtime/application.ex, lib/nerves_runtime/init.ex, lib/nerves_runtime/log/kmsg_tailer.ex, lib/nerves_runtime/log/syslog_tailer.ex
Elixir 1.10's Logger calls only return :ok now, so the return value no
longer needs to be ignored to make Dialyzer happy.
=> Remove _ = on all Logger calls

README.md, lib/nerves_runtime/init.ex
Per #180, #184, #185 and other discussion, this reverts the autovalidate code and replaces it with some text about calling `Nerves.Runtime.validate_firmware/0` in your application.
=> Revert auto-validate code

.circleci/config.yml, mix.exs, mix.lock
This version of `uboot_env` is a potentially breaking update that
supports devices with redundant U-Boot environment configurations. The
API change in it does not affect `nerves_runtime`.
See https://hexdocs.pm/uboot_env/0.3.0/changelog.html#v0-3-0.
=> Support uboot_env ~> 0.3.0

lib/nerves_runtime/kv.ex, lib/nerves_runtime/kv/mock.ex, lib/nerves_runtime/kv/uboot_env.ex
This makes it a little more clear that the KV backend only supports
string keys and values.
=> Tighten up KV specs

.github/CONTRIBUTING.md
The URL was missing a folder in the path, and was producing a 404.
Old URL: https://github.com/nerves-project/nerves/blob/main/CONTRIBUTING.md
New URL: https://github.com/nerves-project/nerves/blob/main/.github/CONTRIBUTING.md
=> Fix URL for the contributing guide

mix.exs
nerve_runtime is depedent on libmnl-dev and have to be installed on debian
based on OS.This instructs user to do so incase libmnl-dev is not avaible
=> capture libmnl-dev dependency error

Makefile, mix.exs
- Reduce Makefile/gcc prints to clean build output
- Rename clean Makefile target to prevent accidents
=> Reduce Makefile prints and protect against make clean accidents

lib/nerves_runtime/init.ex
Match other `mkfs` commands and pass force flag to recreate partition if not mountable.
Looks like I missed this when adding the original `mkfs.f2fs` support.
=> Add force flag to mkfs.f2fs

README.md, lib/nerves_runtime.ex, test/nerves_runtime_test.exs
U-Boot supports running alternative boot commands if the main one fails
too many times. This can be used for trying out firmware updates and has
a couple advantages: 1. It's easier to talk to people who use U-Boot,
but not Nerves, 2. You can set a new firmware to be tried more than once
before reverting, and 3. The U-Boot script is simpler. The second reason
is interesting if aspects of validating a firmware image are out of your
control and it's better to try it a few times "just in case".
To use this feature, you need to update your U-Boot scripts and make
sure that the bootcount feature is enabled. The fwup script also needs
to be adjusted to set "upgrade_available" and "bootcount".
This change has no effect if you're not using the U-Boot "bootcount"
feature.
=> Support U-Boot bootcount/upgrade_available

lib/nerves_runtime.ex, test/nerves_runtime_test.exs
If you think real hard when the firmware validity feature isn't used,
the firmware is implicitly valid. I.e., a reboot keeps the firmware
rather than reverting.
This changes the function to return `true` when it's not valid.
The immediate effect of this is that Raspberry Pi's which don't
auto-revert back on bad firmware will report `true` now.
=> Change firmware_valid? to be valid when not used

lib/nerves_runtime/init.ex, lib/nerves_runtime/mount_parser.ex, test/nerves_runtime/init_test.exs, test/nerves_runtime/mount_parser_test.exs
The purpose of this is to make it more obvious that the mount output
parser works. There were some assumptions in the code that looked like
they'd raise on unexpected output and this should be more whitespace
tolerant if that ever becomes an issue.
=> Extract mount parser to improve test

lib/nerves_runtime/init.ex
There's no need to keep it around since it doesn't do anything after the
application data partition is created.
=> Exit the init process when done

lib/nerves_runtime.ex, lib/nerves_runtime/application.ex, lib/nerves_runtime/power.ex
This moves the reboot and poweroff handling functions to a dedicated
GenServer to address a rare, but observed case where the supervision
tree for the GenServer that called `Nerves.Runtime.reboot` went down.
This ended up killing the reboot process midway and the device didn't
reboot.
The reboot/poweroff code is now in a singleton GenServer. This also
fixes the case where reboot gets called by multiple processes and there
are dualing reboots happening.
=> Decouple and serialize reboot and poweroff calls

lib/nerves_runtime.ex, mix.exs
This starts the process of centralizing application configuration so that it's
easier to see what all is configurable by looking at the code. It's also
important to have the application config documented, but I'm going to tackle
that in a future PR when the KV store update is in. I'm keeping the KV store
update separate since it was a bigger change.
- Move boardid config default to mix.exs
- Make revert_fw_path configurable
=> Centralize application configuration defaults

README.md, lib/nerves_runtime/kv.ex, test/nerves_runtime/kv_test.exs
Turns out we used to support just specifying `Nerves.Runtime.KV.Mock` as
a key in the `:nerves_runtime` application config along with the `:modules`
specification
This adds that backwards compatibility back in
=> Fix supporting backwards compatible `Nerves.Runtime.KV.Mock`

mix.exs
The default in `mix.exs` does not match the expected value of `boardid_path`
https://github.com/nerves-project/nerves_runtime/blob/main/lib/nerves_runtime.ex#L91
=> Fix mismatched `boardid_path` application config option

lib/nerves_runtime/heart.ex, test/nerves_runtime/heart_test.exs
The original fields are still supported, since it will take some time
for Nerves Heart 1.x to work its way out of systems.
=> Support Nerves Heart 2.0 status reports

lib/nerves_runtime.ex, lib/nerves_runtime/heart.ex, lib/nerves_runtime/power.ex
If Nerves Heart 2.0 is available, then the reboot and poweroff functions
will go through it. This has two advantages:
1. If the system is messed up in such a way that cause OS processes to
fail to start, a graceful reboot and poweroff may still work. The
current way is to run Busybox poweroff and reboot.
2. Reboot and Poweroff now stop the hardware watchdog from being petted.
This puts a hard limit on how long they can take.
The other addition is an `init_complete` call to protect the time
between boot and calling `:heart.set_callback/1`. The idea is that you
tell Nerves Heart 2.0 via configuration that it should expect an
initialization complete notification and how long to wait. If time
passes without the notification, Nerves Heart reboots the system since
something is wrong. You call …
=> Support Nerves Heart 2.0 guarded reboot and handshake

lib/nerves_runtime/power.ex
This fixes an issue with the watchdog triggering when the system is supposed to power off.
=> Prevent poweroff from rebooting

lib/nerves_runtime/heart.ex, test/nerves_runtime/heart_test.exs
The difference between heart not running, its queue being blocked and
other heart issues wasn't obvious, so add detail to the errors to make
it easier to see which path was taken.
This also cleans up the threading and versioning when issuing commands.
=> Return more detailed errors on Heart problems

README.md, lib/nerves_runtime.ex, lib/nerves_runtime/fwup_ops.ex, mix.exs, test/fixture/fwup, test/nerves_runtime/fwup_ops_test.exs
This also improves error handling for Nerves.Runtime.revert/1 as a side
effect of it using almost all of the same code as the new helpers.
The new helpers aren't promoted to the Nerves.Runtime interface yet
since they haven't been released in the official Nerves systems.
=> Add helpers for the relatively new fwup ops.fw tasks

lib/nerves_runtime/power.ex
`:init.stop()` returns and it's not supposed to, this might be in newer OTPs only.
=> Add an infinite sleep when calling reboot

lib/nerves_runtime/application.ex, lib/nerves_runtime/power.ex
This cleans up the poweroff code that got a little more complicated with
the guarded poweroff feature. There's no GenServer running and the code
to prevent multiple calls to power off simultanously has been removed
since that doesn't seem to be a big risk. The poweroff is still run in
an process that's not linked to the caller to avoid supervision tree
restarts from halting a poweroff.
This also fixes a bug where control was returned to the caller after an
`:init.stop/0`. The new way is to wait 10 minutes and then call
`:erlang.halt/0` as a last resort. The guarded reboot/poweroff should
kick in before this, though.
=> Simplify and further bulletproof poweroff error cases

lib/nerves_runtime/fwup_ops.ex, lib/nerves_runtime/heart.ex
Since the factory reset mechanism runs in the application environment
(rather than in the bootloader or some more pristine location), it has
to deal with other code accidentally undoing what it does. Graceful
reboot could consistently do this on some configurations and the result
was a really bad partial factory reset. This updates the factory reset
to invoke an immediate reboot feature that was added to Nerves Heart.
=> Support ungraceful reboot and use for factory reset

lib/nerves_runtime/init.ex
The current default behavior is to return filesystem corruption errors
and stay "writable". This seems reasonable, but there's been a history
of remounting read-only on error, so it was surprising when the failure
changed. This restores the failure mode. F2FS does not have a similar
option, so only set it for ext4.
=> Remount ext4 app partition read-only on error

.circleci/config.yml, test/test_helper.exs
This also refreshes the list of other Elixir/Erlang combinations tested
to match the main nerves repository.
=> Test with Elixir 1.18; fix deprecation warning

README.md
It's documented in modules and in `fwup-ops.conf` files, but this seems
like a more findable location. Plus NervesRuntime is the main user.
=> Document the ops.fw file officially

lib/nerves_runtime/fwup_ops.ex, test/nerves_runtime/fwup_ops_test.exs
This exposes the ops.fw's capability of returning which slot is running
and which will be the one that gets run on next boot. This actually has
been around since the ops.fw was added, but it was never exposed.
=> Support returning the current and next boot slots

lib/nerves_runtime/kv.ex, test/nerves_runtime/kv_test.exs
This makes it possible to programmatically reload the cached KV values after an
external program like `fwup` modifies them. This is needed for using `fwup` to
validate or revert firmware since `fwup` runs outside of Elixir.
=> Support external modifications to KV

lib/nerves_runtime.ex
Laundering the target through `Function.identity/1` seems to suffice.
This also removes the directive to silence a Dialyzer warning that really was insufficient.
=> Fix Dialyzer warnings when using mix_target/0

README.md, lib/nerves_runtime/fwup_ops.ex, mix.exs, test/nerves_runtime/fwup_ops_test.exs
The application config had been commonly used in host builds, but never
officially documented. This changes that and fixes two app environment
keys that had unfortunate names, `:env` to `:fwup_env` and
`:revert_fw_path` to `:ops_fw_path`. These really should only have been
used for Nerves.Runtime unit tests.
=> Document application config and make official

README.md, lib/nerves_runtime.ex, lib/nerves_runtime/fwup_ops.ex, lib/nerves_runtime/kv.ex, test/nerves_runtime/fwup_ops_test.exs, test/nerves_runtime_test.exs
This also settles on referring to the slot providing the firmware that's running as `active`. The references to `current` were all updated.
=> Add firmware_slots/0 to get the active and next firmware slots

lib/nerves_runtime/application.ex
This is especially useful for rngd where you may want to disable a source, or pass in a config for another source. For example, while I was investigating some error messages found in dmesg for my Compulab IOT-Gate board, I found that several sources were detected but none were available. This PR allowed me to pass in args to disable many of the sources configured during Nerves.Runtime startup.
=> Allow for args to be passed to `rngd` and `haveged`
